openapi: "3.0.0"
info:
  version: 1.0.0
  title: Claims API
paths:
  /api/claims-data/v1/claims:
    get:
      tags:
        - claims
      summary: Get claims
      operationId: getClaims
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Claims"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    post:
      tags:
        - claims
      summary: Create an claim
      operationId: createClaim
      requestBody:
        description: create an claim
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimRequestBody'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /api/claims-data/v1/claims/{id}:
    get:
      summary: Get claim by id
      operationId: getClaimById
      tags:
        - claims
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the claim to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Claim"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    put:
      tags:
        - claims
      summary: Update an claim
      operationId: updateClaim
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the claim to be updated
          schema:
            type: integer
            format: int64
      requestBody:
        description: update an existing claim
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimRequestBody'
      responses:
        '204':
          description: No content
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    delete:
      summary: Delete claim by id
      operationId: deleteClaim
      tags:
        - claims
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the claim to be deleted
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    Claim:
      required:
        - id
        - name
        - description
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    ClaimRequestBody:
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string

    Claims:
      type: array
      items:
        $ref: "#/components/schemas/Claim"