name: Deploy to Kubernetes
description: Configures kubectl and applies deployment files to a Kubernetes namespace
inputs:
  namespace:
    description: Kubernetes namespace to deploy to
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "${{ env.KUBE_CERT }}" > ca.crt
        kubectl config set-cluster "$KUBE_CLUSTER" --certificate-authority=./ca.crt --server="https://$KUBE_CLUSTER"
        kubectl config set-credentials deploy-user --token="$KUBE_TOKEN"
        kubectl config set-context "$KUBE_CLUSTER" --cluster="$KUBE_CLUSTER" --user=deploy-user --namespace="${{ inputs.namespace }}"
        kubectl config use-context "$KUBE_CLUSTER"
        kubectl -n "${{ inputs.namespace }}" apply -f deployments/
      env:
        KUBE_CERT: ${{ secrets.KUBE_CERT }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}