name: Build and test PR

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test coverage verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Integration test
        run: ./gradlew integrationTest --tests '*IntegrationTest'

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload checkstyle report for claims-data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: claims-data-service/build/reports/checkstyle
          retention-days: 14

      - name: Upload test report for claims-data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: claims-data-service/build/reports/tests
          retention-days: 14

      - name: Upload jacoco coverage report for claims-data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: claims-data-service/build/reports/jacoco
          retention-days: 14

  vulnerability-scan-app:
    runs-on: ubuntu-latest
    needs:
      - build-test
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_TEST_EXCLUDE: build,generated
      SNYK_TARGET_REFERENCE: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          command: code test
          args: --severity-threshold=high

  vulnerability-scan-docker:
    runs-on: ubuntu-latest
    needs:
      - build-test
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build app jar with gradle
        run: ./gradlew build

      - name: Build a Docker image for claims-data
        run: docker build -t laa-data-stewardship-payments/claims-data:scan ./claims-data

      - name: Run Snyk to check claims-data Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        with:
          image: laa-data-stewardship-payments/claims-data:scan
          args: --file=./claims-data/Dockerfile --severity-threshold=high
